
name: Build

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ConorMacBride/install-package@v1.1.0
        with:
          apt: rlwrap
      - uses: actions/checkout@master
      - name: Set up JDK 21
        uses: actions/setup-java@master
        with:
          java-version: '21'
          distribution: 'corretto'
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@master
        with:
          cli: latest
      - name: Build
        run: clj -T:build uber
      - name: Log in to Docker Hub
        uses: docker/login-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Install and configure the Koyeb CLI
        uses: koyeb-community/koyeb-actions@v2
        with:
          api_token: "${{ secrets.KOYEB_API_TOKEN }}"
      - name: Build the Docker slimjar image
        run: docker build -t manudevelopia/clojure-api-poc:latest . -f docker/Dockerfile
      - name: Publish slimjar image built on DockerHub
        run: docker push manudevelopia/clojure-api-poc
      - name: Deploy image to Koyeb
        run: koyeb service redeploy clojure-api-poc/clojure-api-poc
